### ISSUE TITLE
Ability to reset the RoT

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/management-gateway-service#44]
I'm not actually sure of the mechanism needed to do this outside of a Sprot message. I'm also not sure if this is a good idea from a security point of view. However, we do need to reset the RoT after programming an update. I've currently been doing this through SWD, which will not work in production.

**Comment by lzrd** [comment]
RFD 349 includes discussion of using reset during upgrade and rollback of firmware.
I'm adding a sprot message and plumbing it up through the stack.

**Comment by andrewjstone** [comment]
This is done and works with faux-mgs.
