### ISSUE TITLE
MGS: should deliver the identity of the real phase 2 image to the host (running the trampoline image) via the SP/uart

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/management-gateway-service#52]

**Comment by smklein** [comment]
Just wanted to clarify this issue (I know it looks like I filed it, but I think @jgallagher did originally; I just converted it from a "project board" item to an issue):

- When we say "Identify the real phase 2 image", what does this mean? Point to a sled that has it? Transfer it directly? Supply versioning info about it?

**Comment by jgallagher** [comment]
> When we say "Identify the real phase 2 image", what does this mean? Point to a sled that has it? Transfer it directly? Supply versioning info about it?

Supply versioning info about it. The installinator running in the recovery image handles both the actual transfer and finding a sled that has the data, but it needs to be told the version/identity of the image to look for, and that needs to come via MGS.

**Comment by citrus-it** [comment]
The host side of this is https://github.com/oxidecomputer/stlouis/issues/276

I don't think there is a final determination about how the image ID is going to be transferred and made available to installinator - it's likely to either be a separate new RPC call or just included in the trampoline image header and the published to the host devtree. I favour the second option, but either works.
